name: flutter_application
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  charts_flutter: ^0.12.0
  flutter_charts: ^0.5.2
  fl_chart: ^0.69.0
  pie_chart: ^5.4.0 
  percent_indicator: ^4.2.3
  firebase_core: ^3.5.0
  image_picker: ^0.8.4
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.2
  flutter_native_splash: ^2.4.1
  google_nav_bar: ^5.0.6 
  table_calendar: ^3.0.8
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.17.0
  provider: ^6.0.3
  lottie: ^2.0.0
  sqflite: any
  path: any
  flutter_slidable: ^3.1.1
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.4
  shared_preferences: ^2.0.15
  audioplayers: ^6.1.0
  firebase_dynamic_links: ^6.0.9
  flutter_secure_storage: ^8.0.0
  installed_apps: ^1.5.2
  permission_handler: ^10.2.0
  device_apps: ^2.0.4
  speech_to_text: ^6.3.0
  flutter_tts: ^3.6.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_charts: ^21.2.4
  toggle_switch: ^2.3.0
  streak_calendar: ^1.1.2
  liquid_progress_indicator_v2: ^0.5.0
  sliver_tools: ^0.2.12
  easy_sticky_header: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo2.png"
    


    
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  color: "#dde7ee"
  android_12:
    image: assets/logo/logo.png
    icon_background_color: "#dde7ee"
    branding: assets/logo/AttentionLens.png

  web: false
# The following section is specific to Flutter packages.

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/logo/AttentionLens.png
    - assets/images/welcome_page.png
    - assets/images/login.png
    - assets/images/signup.png
    - assets/images/success.png
    - assets/icons/left-arrow.png
    - assets/icons/bin.png
    - assets/icons/dots.png
    - assets/icons/edit-text.png
    - assets/logo/profilePIC.png
    - assets/images/chatWith.gif
    - assets/images/setReminders.gif
    - assets/images/signToGet.gif
    - assets/images/manageTasks.gif
    - assets/images/allFeaturesShower.gif
    - assets/images/chatWithAttena.png
    - assets/images/addTask.png
    - assets/images/viewProgress.png
    - assets/images/todayTask.png
    - assets/images/focus.png
    - assets/images/breakdown.png
    - assets/images/task.png
    - assets/images/productivity.png
    - assets/images/signedAllFeatures.gif
    - assets/images/signedHome.png
    - assets/images/signUpForFeatures.png
    - assets/images/mainCrousel.png
    - assets/images/managaTasksCrousel.png
    - assets/images/setRemindersCrousel.png
    - assets/images/chatCrousel.png
    - assets/animations/loading.json
    - assets/images/empty_list.png
    - assets/images/done.png
    - assets/images/logo.png
    - assets/images/welcomeChatbot.png
    - assets/images/chatProfile.png
    - assets/sounds/countdown-timer.wav
    - assets/sounds/simple-notification.mp3
    - assets/images/check.png
    - assets/images/arrow.png
    - assets/images/emailSend.png
    - assets/images/initialPage.png
    - assets/images/greyLogo.png
    - assets/sounds/nature-morning.mp3
    - assets/sounds/calming-rain.mp3
    - assets/sounds/white-noise.mp3
    - assets/sounds/midnight.mp3
    - assets/sounds/sea-wave.mp3
    - assets/sounds/flowing-water.mp3
    - assets/images/session_bot.png

    


  # To add assets to your application, add an assets section, like this:
    
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
   
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


